RDMA soft_RoCE implement
seladb/PcapPlusPlus pull request #1583
Opened 2024-09-17 14:39 UTC by FlashBarryAllen

2024-09-19 09:22 UTC, Dimi1010 requested changes
Hello, thanks for your work for this PR. Unfortunately there are a couple of issues with it that need to be addressed.

As per [CONTRIBUTING.md](https://github.com/seladb/PcapPlusPlus/blob/master/CONTRIBUTING.md) all PRs must be merged into `dev` and not `master`. The CI is also configured to run tests on PR's targeting the `dev` branch. I have switched the base of the PR to be `dev` instead, but please pull the changes from the newest `dev` head into your feature branch. It would also allow the CI to update and run the automatic tests against the changes.

I have also included a couple of suggestions to the code, that I noticed while looking through it.

2024-09-19 09:22 UTC, Dimi1010 commented on Packet++/src/InfiniBandLayer.cpp
> +	}
Using `std::to_string(x)` when converting single values is more efficient then using a `std::stringstream`.

2024-09-19 09:22 UTC, Dimi1010 commented on Tests/Packet++Test/TestDefinition.h
> +PTF_TEST_CASE(InfiniBandPacketParsing);
Missing new line at the end of file.
```suggestion
PTF_TEST_CASE(InfiniBandPacketParsing);

```

2024-09-19 09:22 UTC, Dimi1010 commented on Packet++/header/InfiniBandLayer.h
> +            return (rxe_bth*)m_Data;
Cpp style casts are preferred, as they are more explicit.
```suggestion
            return reinterpret_cast<rxe_bth*>(m_Data);
```

2024-09-19 09:22 UTC, Dimi1010 commented on Packet++/src/InfiniBandLayer.cpp
> +		rxe_bth* bthHdr = (rxe_bth*)m_Data;
ditto, C-cast -> Cpp casts

2024-09-21 19:40 UTC, tigercosmos commented
@FlashBarryAllen  Could you update the PR description? also, please run `pre-commit` first. You can find more information in [CONTRIBUTING.md](https://github.com/seladb/PcapPlusPlus/blob/master/CONTRIBUTING.md) as @Dimi1010 has mentioned.

2024-10-02 08:43 UTC, seladb commented
@FlashBarryAllen do you have time to continue working on this PR?

2024-10-04 06:55 UTC, FlashBarryAllen commented
@seladb the next 2 days I have time to implement the left code.

2024-10-04 07:10 UTC, closed without merging