Update Connection Info endTime for every tcp packet arrived
seladb/PcapPlusPlus pull request #850
Opened 2022-03-25 19:23 UTC by leoparente

2022-03-25 20:51 UTC, leoparente commented
@seladb one test failed but I don't know why:
```TestGetMacAddress             : FAILED (Tests/IpMacTests.cpp:309). Assert NOT EQUAL failed: actual: [00:00:00:00:00:00] == expected: [00:00:00:00:00:00]```

2022-03-28 08:11 UTC, seladb approved these changes

2022-03-28 08:14 UTC, seladb requested changes
Maybe add a few tests in [`TcpReassemblyTests.cpp`](https://github.com/seladb/PcapPlusPlus/blob/master/Tests/Pcap%2B%2BTest/Tests/TcpReassemblyTests.cpp)?
There are a few places calling `getConnectionInformation()`

2022-03-29 05:25 UTC, seladb approved these changes

2022-03-29 05:25 UTC, merged

2022-03-29 05:27 UTC, seladb commented
BIG THANK YOU for your contribution @leoparente , much appreciated! 🙏 🙏