Fixes Stack-buffer-overflow WRITE in pcpp::IDnsResource::decodeName
seladb/PcapPlusPlus pull request #913
Opened 2022-07-17 21:01 UTC by sashashura

Fixes Stack-buffer-overflow WRITE in pcpp::IDnsResource::decodeName:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=43847

When decoded name perfectly fits 256 char buffer, so that [255] == '.' the `resultPtr` points exactly past the buffer and `resultPtr[0] = 0;` results in off by one write violation.

2022-07-18 07:08 UTC, seladb requested changes
Thank you @sashashura for working on this bug!

Can you please add the test case attached to the issue to PcapPlusPlus fuzzing tests?
Here's how to do it:
- Download the test case: https://oss-fuzz.com/download?testcase_id=5814090897948672
- Add it to the regression samples: https://github.com/seladb/PcapPlusPlus/tree/master/Tests/Fuzzers/RegressionTests/regression_samples
- Make sure the fuzzing tests run the example and pass, you can view the test results in it in CirrusCI ([here](https://cirrus-ci.com/task/5932500122861568) is an example):
  - [Address sanitizer](https://github.com/seladb/PcapPlusPlus/blob/f6d57cf25d4f63cac75aa4bd6c707448e609121f/.cirrus.yml#L54)
  - [Undefined behavior sanitizer](https://github.com/seladb/PcapPlusPlus/blob/f6d57cf25d4f63cac75aa4bd6c707448e609121f/.cirrus.yml#L66)
- Can you do it for the other PRs as well?

2022-07-18 09:47 UTC, sashashura commented
Nice infrastructure you have! That was extremely easy.

2022-07-19 08:48 UTC, seladb approved these changes

2022-07-19 08:48 UTC, merged

2022-07-19 08:54 UTC, seladb commented
> Nice infrastructure you have! That was extremely easy.

Thank you! I really appreciate the feedback and your contribution to this project! 🙏 ❤️